### ISSUE TITLE
Long polling messages get

### ISSUE THREAD

**Issue by nikepan** [nikepan/govkbot#3]
Make possible use long pooling api. It can use, if no many messages

**Comment by Firues** [comment]
Рили. Где лонгполл, ребят? :) Пожааалуйста.

**Comment by nikepan** [comment]
Спасибо) Не нужен был, потому не делал. Попробую сделать в ближайшее время

**Comment by nikepan** [comment]
вроде все ок

**Comment by nikepan** [comment]
#4

**Comment by Firues** [comment]
ого
